FROM ubuntu

RUN apt-get update && apt-get install -y git make build-essential

WORKDIR /tmp
RUN git clone https://github.com/saper/sassc.git; \
  cd sassc; \
  git checkout bootstrap0; \
  git pull --ff-only origin bootstrap0; \
  . bootstrap.sh; \
  make; \
  make install; \
  cd /tmp && rm -rf sassc

CMD [ "sassc", "--help" ]
