FROM ubuntu

RUN apt-get update && apt-get install -y curl make build-essential

WORKDIR /tmp
RUN curl -L https://github.com/sass/libsass/archive/3.3.6.tar.gz | tar -xz; \
  cd libsass-3.3.6; \
  curl -L https://github.com/sass/sassc/archive/3.3.6.tar.gz | tar -xz; \
  cd sassc-3.3.6; \
  make && make install; \
  cd /tmp && rm -rf libsass-3.3.6

CMD [ "sassc", "--help" ]
