FROM ubuntu

RUN apt-get update && apt-get install -y curl make build-essential

WORKDIR /tmp
RUN curl -L https://github.com/sass/sassc/archive/3.3.6.tar.gz | tar -xz; \
  cd sassc-3.3.6; \
  bash script/bootstrap; \
  cd /tmp && rm -rf sassc-3.3.6

CMD [ "sassc", "--help" ]
