FROM ubuntu

RUN apt-get update && apt-get install -y git make build-essential

WORKDIR /tmp
RUN git clone https://github.com/sass/libsass.git; \
  cd libsass; \
  git clone https://github.com/sass/sassc.git; \
  cd sassc; \
  make && make install; \
  cd /tmp && rm -rf libsass

CMD [ "sassc", "--help" ]
