FROM ubuntu

RUN apt-get update && apt-get install -y git make build-essential

WORKDIR /tmp
RUN git clone https://github.com/sass/sassc.git; \
  cd sassc; \
  bash script/bootstrap; \
  cd /tmp && rm -rf sassc

CMD [ "sassc", "--help" ]
